version: "3"
services:
  server:
    build: ./server/
    environment:
     - PGUSER=${POSTGRES_USER}
     - PGDATABASE=${POSTGRES_DB}
     - PGPASSWORD=${POSTGRES_PASSWORD}
     - PORT=${SERVER_PORT}
     - NODE_END=${NODE_ENV}
    ports:
      - "8001:3000"
      - "9229:9229"
    depends_on:
      - db
  # flyway manages database migrations on the db container
  flyway:
    image: boxfuse/flyway:5.2.4
    command: -url=jdbc:postgresql://db:5432/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations-sql:/flyway/sql
    depends_on:
      - db
  db:
    image: "postgres"
    container_name: "matcha_postgres"
    restart: always
    environment:
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_DB=${POSTGRES_DB}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "8002:5432"
#   Set a volume some that database is not lost after shutting down the container.
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
